[package]
name = "lua_config_utils"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
latest_bin = { path = "../latest_bin" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }
mlua = { workspace = true }
shellexpand = { workspace = true }

[dev-dependencies]
regex = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }
test_utils = { workspace = true }
fixturify = { workspace = true }

[lints]
workspace = true
